### ISSUE TITLE
Issue with creating filenames_accident in 2_Dataset_Preperation

### ISSUE THREAD

**Issue by zosob** [Giffy/CarCrashDetector#3]
Before part 4 of the code, the code has this part.

   `filenames_accident = !ls {PATH}/Accidents` 

gives filenames from the folder, which outputs as

` [   'frame1000.png\tframe15320.png\tframe436.png  frame572.png  frame680.png',  'frame1004.png\tframe15324.png\tframe440.png  frame576.png  frame684.png', ...]`

The \t in the name of the frames messes the code up going ahead. I wanted to know if you faced the same issue. 

If you did, could you please help me out? If you didn't, you you still try please?

**Comment by Giffy** [comment]
Hi,
When I run it, it worked without any problem. It seems that some changes have been done in Google Colab.
I corrected the code doing the list of directory with python os library.  (os.listdir)
I'll upload corrected ASAP.
Regards

**Comment by zosob** [comment]
Hello,

Thank you for the quick response. Maybe it is an issue with my dataset. What is the dataset that you are using?

**Comment by Giffy** [comment]
I reviewed updated and solved your problem.
I corrected directory listing (using python os library instead of linux command) and updated Google Drive link.
I hope will help you
